In [70]:
%config IPCompleter.greedy = True

In [71]:
import numpy as np

In [72]:
data_i = np.arange(5)
data_i

array([0, 1, 2, 3, 4])

In [73]:
data_ii = np.array([False, False, True, True, True])
data_ii

array([False, False,  True,  True,  True])

In [74]:
data_iii = data_i[data_ii]
data_iii

array([2, 3, 4])

 ---
 - data_i is an array and doing any boolean expression opeartion is vectorized operation that returns an array of Boolean.

In [75]:
data_iv = data_i[data_i % 2 == 0]
data_iv

array([0, 2, 4])