In [22]:
%config IPCompleter.greedy = True

In [23]:
import numpy as np

In [24]:
data_i = np.arange(5)
data_i

array([0, 1, 2, 3, 4])

In [25]:
data_ii = np.array([False, False, True, True, True])
data_ii

array([False, False,  True,  True,  True])

In [26]:
data_iii = data_i[data_ii]
data_iii

array([2, 3, 4])

In [27]:
data_iv = data_i[data_i % 2 == 0]
data_iv

array([0, 2, 4])